create table if not exists public.rab_reviews (
  id bigint generated by default as identity primary key,
  app_slug text not null,
  name text not null,
  rating integer not null check (rating between 1 and 5),
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.rab_reviews enable row level security;

drop policy if exists "Anyone can read RAB Store reviews" on public.rab_reviews;
create policy "Anyone can read RAB Store reviews"
  on public.rab_reviews for select using (true);

drop policy if exists "Anyone can publish RAB Store reviews" on public.rab_reviews;
create policy "Anyone can publish RAB Store reviews"
  on public.rab_reviews for insert with check (true);

create table if not exists public.rab_downloads (
  id bigint generated by default as identity primary key,
  app_slug text not null,
  created_at timestamptz not null default now()
);

alter table public.rab_downloads enable row level security;

drop policy if exists "Anyone can count RAB Store downloads" on public.rab_downloads;
create policy "Anyone can count RAB Store downloads"
  on public.rab_downloads for select using (true);

drop policy if exists "Anyone can record RAB Store downloads" on public.rab_downloads;
create policy "Anyone can record RAB Store downloads"
  on public.rab_downloads for insert with check (true);
